--------------------------------------------------------
-- Archivo creado  - martes-febrero-24-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "ADMIN1"."CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"TIPO" VARCHAR2(30 BYTE), 
	"ACTIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ERRORES_AUDIT
--------------------------------------------------------

  CREATE TABLE "ADMIN1"."ERRORES_AUDIT" 
   (	"USUARIO" VARCHAR2(50 BYTE), 
	"ORIGEN" VARCHAR2(50 BYTE), 
	"FECHA" DATE, 
	"VERROR" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACTURA
--------------------------------------------------------

  CREATE TABLE "ADMIN1"."FACTURA" 
   (	"ID_FACTURA" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_USUARIO" NUMBER, 
	"FECHA" DATE, 
	"TOTAL" NUMBER, 
	"ESTADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENSAJE_TRIGGERS
--------------------------------------------------------

  CREATE TABLE "ADMIN1"."MENSAJE_TRIGGERS" 
   (	"VUSER" VARCHAR2(50 BYTE), 
	"VMENSAJE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ADMIN1"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_CATEGORIA" NUMBER, 
	"NOMBRE" VARCHAR2(1000 BYTE), 
	"DESCRIPCION" VARCHAR2(1600 BYTE), 
	"PRECIO" NUMBER, 
	"EXISTENCIAS" NUMBER, 
	"RUTA_IMAGEN" VARCHAR2(2048 BYTE), 
	"ACTIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "ADMIN1"."ROLES" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "ADMIN1"."USUARIO" 
   (	"ID_USUARIO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO" VARCHAR2(100 BYTE), 
	"CORREO" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(2048 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"TARJETA" VARCHAR2(16 BYTE), 
	"PIN" VARCHAR2(4 BYTE), 
	"FECHA" DATE, 
	"ACTIVO" NUMBER(1,0), 
	"ID_ROL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "ADMIN1"."VENTA" 
   (	"ID_VENTA" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_FACTURA" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"PRECIO" NUMBER, 
	"CANTIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN1.CATEGORIA
SET DEFINE OFF;
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('1','Naruto','Anime','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('2','Dragon Ball','Anime','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('3','One Piece','Anime','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('4','Mario Bros','Videojuegos','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('5','Fnaf','Videojuegos','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('6','Plantas vs Zombies','Videojuegos','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('7','Polar','Osos','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('8','Panda','Osos','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('9','Escandalosos','Osos','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('10','Otros','Osos','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('11','My Melody','MyMelody','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('12','Cinnamoroll','MyMelody','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('13','Kuromi','MyMelody','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('14','Pompompuri','MyMelody','1');
Insert into ADMIN1.CATEGORIA (ID_CATEGORIA,NOMBRE,TIPO,ACTIVO) values ('15','Hello Kitty','MyMelody','1');
REM INSERTING into ADMIN1.ERRORES_AUDIT
SET DEFINE OFF;
REM INSERTING into ADMIN1.FACTURA
SET DEFINE OFF;
Insert into ADMIN1.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL,ESTADO) values ('1','1',to_date('05/01/22','DD/MM/RR'),'211560','2');
Insert into ADMIN1.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL,ESTADO) values ('2','2',to_date('07/01/22','DD/MM/RR'),'554340','2');
Insert into ADMIN1.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL,ESTADO) values ('3','3',to_date('07/01/22','DD/MM/RR'),'871000','2');
Insert into ADMIN1.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL,ESTADO) values ('4','1',to_date('15/01/22','DD/MM/RR'),'244140','1');
Insert into ADMIN1.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL,ESTADO) values ('5','2',to_date('17/01/22','DD/MM/RR'),'414800','1');
Insert into ADMIN1.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL,ESTADO) values ('6','3',to_date('21/01/22','DD/MM/RR'),'420000','1');
REM INSERTING into ADMIN1.MENSAJE_TRIGGERS
SET DEFINE OFF;
REM INSERTING into ADMIN1.PRODUCTO
SET DEFINE OFF;
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('1','1','Peluche Naruto 25cm','Muñeco de peluche de Naruto para niños, juguete coleccionable de anime,  regalo de cumpleaños y navidad, 25cm','18,24','5','https://www.king-jouet.com/fstrz/r/s/images.king-jouet.com/6/gu909093_6.jpg?frz-v=3234','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('2','1','Peluche Sasuke 25cm','Muñeco de peluche de Sasuke para niños, juguete coleccionable de anime,  regalo de cumpleaños y navidad, 25cm','18,24','10','https://media.entertainmentearth.com/assets/images/b5b9233b5fbb43e4be9dc40966ef3f80lg.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('3','1','Peluche Kakashi 25cm','Muñeco de peluche de Kakashi para niños, juguete coleccionable de anime,  regalo de cumpleaños y navidad, 25cm','18,24','3','https://www.cadeau-naruto.com/wp-content/uploads/2023/11/peluche-kakashi-hatake.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('4','1','Peluche Sakura','Muñeco de peluche de Sakura para niños, regalo de cumpleaños y navidad','15,3','15','https://i.ebayimg.com/images/g/1egAAOSwJLBiSsBC/s-l1600.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('5','1','Peluche Hinata 25cm','Muñeco de peluche de Hinata para niños, juguete coleccionable de anime,  regalo de cumpleaños y navidad','18,24','7','https://baseec-img-mng.akamaized.net/images/item/origin/b834a5566407f66b1f3dac5aaa258092.jpg?imformat=generic','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('6','2','Peluche Goku 25cm','Muñeco de peluche de Goku para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad','18,24','9','https://i.pinimg.com/736x/27/ea/b2/27eab2aa35434a3234acad1356e5d4ef--dragon-ball-z-plushies.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('7','2','Peluche Vegeta 25cm','Muñeco de peluche de Vegeta para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad','15','10','https://m.media-amazon.com/images/I/715ommdiKJL._AC_SY606_.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('8','2','Peluche Piccolo 25cm','Muñeco de peluche de Vegeta para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad','20','5','https://i5.walmartimages.com/asr/894534e7-9d88-4ecf-a627-0a393d0e3550.4bab59009d7d7bfcc9e4c832d53e56f3.jpeg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('9','2','Peluche Freezer 15cm','Muñeco de peluche de Freezer para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad','17,5','6','https://tiendadfanatic.com/wp-content/uploads/2021/04/Peluche-Freezer-Dragon-Ball-Z-15cm.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('10','2','Peluche Bulma 30cm','Muñeco de peluche de Bulma para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad','22','11','https://todomasbarato.es/6458-thickbox_default/peluche-de-bulma-de-dragon-ball-z-30-cm-nuevo-con-etiquetas-chica-madre-goku.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('11','3','Peluche Luffy 20cm','Muñeco de peluche de Luffy para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad','18,24','20','https://www.figurine-discount.com/46208-thickbox_default/one-piece-peluche-luffy-20-cm.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('12','3','Peluche Chopper 25cm','Muñeco de peluche de Chopper para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad','15','11','https://www.figurine-discount.com/22042-thickbox_default/one-piece-peluche-chopper-25-cm.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('13','3','Peluche Zoro 25cm','Muñeco de peluche de Zoro para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad','20','24','https://okocollection.fr/1038-large_default/one-piece-peluche-sanji.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('14','3','Peluche Sanji 30cm','Muñeco de peluche de Sanji para niños, juguete coleccionable del anime, regalo de cumpleaños y navidad','17,5','5','https://www.cdiscount.com/pdt2/5/8/8/1/550x550/fp3701315823588/rw/peluche-one-piece-sanji-30-cm.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('15','4','Peluche de hongo','Muñeco de peluche de hongo para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 25cm','18,24','2','https://trebolmayoreo.com/wp-content/uploads/2022/06/100002001-Peluche-Hongo-verde-grande-fino.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('16','4','Peluche de Luigi','Muñeco de peluche de Luigi para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 25cm','15','4','https://i.pinimg.com/originals/dd/f0/63/ddf0634dc5c6dddbcd979011016b508b.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('17','4','Peluche de Princesa Peach','Muñeco de peluche de Princesa Peach para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 25cm','10','30','https://i.pinimg.com/originals/a1/f3/a8/a1f3a8d70bf1daf7cc9f127ec4283a08.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('18','4','Peluche de Bowser','Muñeco de peluche de Bowser para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 30cm','17,5','10','https://www.buildabear.cl/wp-content/uploads/2022/02/23566.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('19','4','Peluche de Yoshi','Muñeco de peluche de Yoshi para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 25cm','22','5','https://cdn.idealo.com/folder/Product/203164/8/203164847/s11_produktbild_max/san-ei-super-mario-bros-peluches-yoshi.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('20','5','Peluche de Bonnie the Bonnie','Muñeco de peluche de Bonnie the Bonnie para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 20cm','16','5','https://cdnx.jumpseller.com/aratoystore/image/12602876/resize/540/540?1648671306','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('21','5','Peluche de Foxy the Pirate Fox','Muñeco de peluche de Foxy the Pirate Fox para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 20cm','10','5','https://http2.mlstatic.com/D_NQ_NP_781779-MLC73509665107_122023-O.webp','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('22','5','Peluche de High Score Toy Chica','Muñeco de peluche de High Score Toy Chica para niños, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 20cm','17,5','10','https://videodis.es/46413-large_default/peluche-five-nights-at-freddy-s-high-score-chica-inverted-18-cm.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('23','6','Peluche de Zombie','Muñeco de peluche de Zombie, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 30cm','16','10','https://promart.vteximg.com.br/arquivos/ids/384411-1000-1000/46.jpg?v=637127139349830000','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('24','6','Peluche de Girasol','Muñeco de peluche de Girasol, juguete coleccionable del videojuego, regalo de cumpleaños y navidad, 30cm','10','3','https://ae01.alicdn.com/kf/Hed5f799b4b9b4af79c6e9c0fccb57374Q.jpg_640x640Q90.jpg_.webp','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('25','11','Cinnamoroll con pijama','Muñeco de peluche de MyMelody Cinnamoroll con un pijama azul, juguete coleccionable de MyMelody, regalo de cumpleaños y navidad, 20cm','18,24','20','https://http2.mlstatic.com/D_NQ_NP_880946-MLC69930227264_062023-O.webp','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('26','11','Kuromi traje original','Muñeco de peluche de MyMelody Kuromi, juguete coleccionable de MyMelody, regalo de cumpleaños y navidad, 15cm','16','10','https://i.pinimg.com/736x/79/6a/a6/796aa657a7f88e9f109b52b94d43af4e.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('27','11','Pompompuri (Gato)','Muñeco de peluche de MyMelody Pompompuri con un traje de Gato, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm','16,5','21','https://i.pinimg.com/736x/10/9d/40/109d407ab6eed35663a8bccfce571613.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('28','11','Cinnamoroll traje GODIVA 2023','Muñeco de peluche de MyMelody Cinnamoroll con traje de GODIVA 2023, juguete coleccionable de MyMelody, regalo de cumpleaños y navidad, 22cm','18','10','https://happycruise.jp/wp-content/uploads/2023/01/valentine2023-sanrio-godiva12.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('29','12','Peluche de Cinnamoroll con pijama','Muñeco de peluche de Cinnamoroll con un pijama azul, juguete coleccionable de Cinnamoroll, regalo de cumpleaños y navidad, 20cm','18,24','20','https://http2.mlstatic.com/D_NQ_NP_880946-MLC69930227264_062023-O.webp','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('30','12','Cinnamoroll (Enamorado)','Muñeco de peluche de Cinnamoroll con traje azul y destellos en los ojos, juguete coleccionable de Cinnamoroll, regalo de cumpleaños y navidad, 15cm','18','10','https://meccha-japan.com/557634-large_default/plush-cinnamoroll-sanrio-birthday-2024.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('31','12','Peluche de Cinnamoroll (Fresas Season)','Muñeco de peluche de Cinnamoroll con traje de colores pasteles y fresas, juguete coleccionable de Cinnamoroll, regalo de cumpleaños y navidad, 20cm','15,5','10','https://i.ebayimg.com/images/g/hJ8AAOSwprNi731R/s-l1600.png','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('32','12','Cinnamoroll 20 Aniversario','Muñeco de peluche de Cinnamoroll con traje alusivo al 20 aniversario, juguete coleccionable de Cinnamoroll, regalo de cumpleaños y navidad, 26cm','18,5','10','https://meccha-japan.com/248937-large_default/peluche-kotekikai-cinnamoroll-20th.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('33','12','Peluche de Cinnamoroll (Traje GODIVA 2023)','Muñeco de peluche de Cinnamoroll con traje de GODIVA 2023, juguete coleccionable de MyMelody, regalo de cumpleaños y navidad, 22cm','18','10','https://happycruise.jp/wp-content/uploads/2023/01/valentine2023-sanrio-godiva12.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('34','13','Peluche de Kuromi (Traje lila)','Muñeco de peluche de Kuromi con traje color lila y detalles rosita, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm','19','18','https://i.etsystatic.com/10186101/r/il/ec4661/3150024846/il_fullxfull.3150024846_khvt.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('35','13','Peluche de Kuromi (Traje original)','Muñeco de peluche de Kuromi con su traje original, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm','16','15','https://i.pinimg.com/736x/79/6a/a6/796aa657a7f88e9f109b52b94d43af4e.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('36','13','Peluche de Kuromi (Gala Gotica)','Muñeco de peluche de Kuromi con un traje de gala negro con rojo y detalle decorativo en su orejita, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm','17,3','17','https://img.shoplineapp.com/media/image_clips/64a4478bb489f20011a75d67/original.jpg?1688487819','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('37','13','Peluche de Kuromi (Negro Elegancia)','Muñeco de peluche de Kuromi con traje de gala color negro y detalles en el mismo color, juguete coleccionable de Kuromi, regalo de cumpleaños y navidad, 22cm','16,5','21','https://d2bzx2vuetkzse.cloudfront.net/unshoppable_producs/ad320ac8-4e02-4834-a5fa-6acaf3048f25.jpeg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('38','14','Peluche de Pompompuri (Vaca)','Muñeco de peluche de Pompompuri con un traje de Vaca, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm','16','21','https://cdn.shopify.com/s/files/1/0416/8083/0620/products/184420-Zoom.1_1600x.jpg?v=1613076991','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('39','14','Peluche de Pompompuri (Gato)','Muñeco de peluche de Pompompuri con un traje de Gato, juguete coleccionable de Pompompuri, regalo de cumpleaños y navidad, 22cm','16,5','21','https://i.pinimg.com/736x/10/9d/40/109d407ab6eed35663a8bccfce571613.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('40','15','Peluche de Hello Kitty (Traje original)','Muñeco de peluche de Hello Kitty con el traje original, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm','9','21','https://gadgetsin.com/uploads/2010/10/sanrio_dancing_hello_kitty_speaker_1.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('41','15','Peluche de Hello Kitty (Traje original rosado)','Muñeco de peluche de Hello Kitty con el traje original version rosado, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm','11','21','https://meccha-japan.com/195143-large_default/plush-howa-howa-2l-hello-kitty.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('42','15','Peluche de Hello Kitty (Pijama)','Muñeco de peluche de Hello Kitty con un pijama rosita, juguete coleccionable de Hello Kitty, regalo de cumpleaños y navidad, 22cm','10','21','https://i.pinimg.com/originals/54/f6/02/54f602190af0d8185043267a21ded238.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('43','7','Peluche de Polar (Normal)','Muñeco de peluche de Polar normal, juguete coleccionable de escandalosos , regalo de cumpleaños y navidad, 22cm','10','9','https://media.entertainmentearth.com/assets/images/6227c1ee4dd74cb2ba4323bae9648f0blg.jpg?_gl=1*18p7dfe*_ga*NjQwOTk1MzY1LjE3MTAyMTgxMDE.*_ga_M8MT85W31R*MTcxMzg1NjMzNS4yLjAuMTcxMzg1NjMzNS42MC4wLjA.','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('44','7','Peluche de Polar (Cumpleañero)','Muñeco de peluche de Polar Cumpleañero, juguete coleccionable de escandalosos , regalo de cumpleaños y navidad, 22cm','10','9','https://miniso-bh.com/wp-content/uploads/2021/05/2010143612105_1.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('45','8','Peluche de Panda (Normal)','Muñeco de peluche de Polar Normal, juguete coleccionable de escandalosos , regalo de cumpleaños y navidad, 22cm','10','9','https://f.fcdn.app/imgs/fbe799/www.minisouruguay.com.uy/miniuy/6828/webp/catalogo/694105513216969410551321761/600x600/peluche-sentado-escandalosos-panda.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('46','9','Peluches de Escandalosos','Muñecos de peluche de escandalosos, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm','10','9','https://http2.mlstatic.com/D_NQ_NP_924964-MLA54979793842_042023-O.webp','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('47','9','Peluches de Escandalosos (Apilados)','Muñecos de peluche de escandalosos apilados, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm','10','9','https://http2.mlstatic.com/D_NQ_NP_921822-MLM51330080109_082022-O.webp','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('48','9','Peluches de Escandalosos (Frutas)','Muñecos de peluche de escandalosos frutas, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm','10','9','https://www.peluchesymas.com/wp-content/uploads/2021/05/as.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('49','10','Peluches de Ositos Cariñositos (Gruñosito)','Muñeco de peluche de cariñosito, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm','10','10','https://http2.mlstatic.com/D_NQ_NP_873801-MCO44201264752_112020-O.webp','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('50','10','Peluches de Ositos Cariñositos (Amorosita)','Muñeco de peluche de amorosita, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm','10','10','https://i.pinimg.com/564x/5e/3a/53/5e3a53fd33cf4c8be5c728c8ef8a079b.jpg','1');
Insert into ADMIN1.PRODUCTO (ID_PRODUCTO,ID_CATEGORIA,NOMBRE,DESCRIPCION,PRECIO,EXISTENCIAS,RUTA_IMAGEN,ACTIVO) values ('51','10','Peluches de Ositos Cariñositos (Dormilonsito)','Muñeco de peluche de dormilonsito, juguetes coleccionables de escandalosos , regalo de cumpleaños y navidad, 22cm','10','10','https://m.media-amazon.com/images/I/71HfOYloy+L.SS700.jpg','1');
REM INSERTING into ADMIN1.ROLES
SET DEFINE OFF;
Insert into ADMIN1.ROLES (ID,NOMBRE) values ('1','ROLE_ADMIN');
Insert into ADMIN1.ROLES (ID,NOMBRE) values ('2','ROLE_USER');
REM INSERTING into ADMIN1.USUARIO
SET DEFINE OFF;
Insert into ADMIN1.USUARIO (ID_USUARIO,NOMBRE,APELLIDO,CORREO,DIRECCION,USERNAME,PASSWORD,TARJETA,PIN,FECHA,ACTIVO,ID_ROL) values ('1','Laura','Mariloca','Laura@example.com','Heredia Centro','user_123','$2a$12$04CrX/liDFv9De2pwewjH.V54GWW.4aa/LrZJwetwXn5otlGFPv7.','****-1111','1234',to_date('15/04/30','DD/MM/RR'),'1','2');
Insert into ADMIN1.USUARIO (ID_USUARIO,NOMBRE,APELLIDO,CORREO,DIRECCION,USERNAME,PASSWORD,TARJETA,PIN,FECHA,ACTIVO,ID_ROL) values ('2','Alondra','Loriaa','alon123@example.com','Llanos del Sol','user_456','$2a$12$Iaz69g9rD9tzKO0kaB.V/.UkwIRHMPr9nPU1kCM7jc.9.wkRrx7Yi','****-2222','5678',to_date('15/04/28','DD/MM/RR'),'1','2');
Insert into ADMIN1.USUARIO (ID_USUARIO,NOMBRE,APELLIDO,CORREO,DIRECCION,USERNAME,PASSWORD,TARJETA,PIN,FECHA,ACTIVO,ID_ROL) values ('3','Carlos','Jimenez','jimenez@example.com','Calle Sánchez','user_789','$2a$12$stCHKC9z1UJs3rDa2kisfucZnHTXruTuNJwsOILv5bzLOMdc9cRkG','****-3333','9101',to_date('15/04/29','DD/MM/RR'),'1','2');
Insert into ADMIN1.USUARIO (ID_USUARIO,NOMBRE,APELLIDO,CORREO,DIRECCION,USERNAME,PASSWORD,TARJETA,PIN,FECHA,ACTIVO,ID_ROL) values ('4','Admin','Admin','admin@example.com','La Aurora','admin','$2a$12$mwkEba3Ge19v4g1dIN3pmuT2oDVyd51NWDHpquHq4wdVeesbcVBBC','****-4444','1314',to_date('15/04/32','DD/MM/RR'),'1','1');
REM INSERTING into ADMIN1.VENTA
SET DEFINE OFF;
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('1','1','5','45000','3');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('2','1','9','15780','2');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('3','1','10','15000','3');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('4','2','5','45000','1');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('5','2','14','154000','3');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('6','2','9','15780','3');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('7','3','14','154000','1');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('8','3','6','57000','1');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('9','3','15','330000','2');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('10','1','6','57000','2');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('11','1','8','27600','3');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('12','1','9','15780','3');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('13','2','8','27600','3');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('14','2','14','154000','2');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('15','2','3','24000','1');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('16','3','15','330000','1');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('17','3','12','45000','1');
Insert into ADMIN1.VENTA (ID_VENTA,ID_FACTURA,ID_PRODUCTO,PRECIO,CANTIDAD) values ('18','3','10','15000','3');
--------------------------------------------------------
--  DDL for Trigger TRG_PRODUCTOS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "ADMIN1"."TRG_PRODUCTOS" 
    AFTER UPDATE OR INSERT OR DELETE ON Producto
    FOR EACH ROW
DECLARE
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN

    IF DELETING THEN
        INSERT INTO MENSAJE_TRIGGERS VALUES(USER,' SE HA BORRADO UN PRODUCTO:'|| :OLD.id_producto ||' '|| :OLD.nombre);
    ELSIF UPDATING THEN
        INSERT INTO MENSAJE_TRIGGERS VALUES(USER,' SE HA ACTUALIZADO UN PRODUCTO:'|| :OLD.id_producto ||' '|| :OLD.nombre||' '||:OLD.existencias||' '||:NEW.existencias);
    ELSIF INSERTING THEN
        INSERT INTO MENSAJE_TRIGGERS VALUES(USER,' SE HA INSERTADO UN PRODUCTO'|| :NEW.id_producto ||' '|| :NEW.nombre||' '||:NEW.existencias); 
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'TRG_PRODUCTOS', SYSDATE, VCOD || ' - ' || VMES);
END; 
/
ALTER TRIGGER "ADMIN1"."TRG_PRODUCTOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "ADMIN1"."TRG_USER" 
    AFTER UPDATE OR INSERT OR DELETE ON Usuario
    FOR EACH ROW
DECLARE
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN

    IF DELETING THEN
        INSERT INTO MENSAJE_TRIGGERS VALUES(USER,' SE HA BORRADO UN USUARIO:'|| :OLD.id_usuario ||' '|| :OLD.nombre||' '||:OLD.username);
    ELSIF UPDATING THEN
        INSERT INTO MENSAJE_TRIGGERS VALUES(USER,' SE HA ACTUALIZADO UN USUARIO:'|| :OLD.id_usuario ||' '|| :OLD.nombre||' '||:OLD.username);
    ELSIF INSERTING THEN
        INSERT INTO MENSAJE_TRIGGERS VALUES(USER,' SE HA INSERTADO UN USUARIO'|| :NEW.id_usuario ||' '|| :NEW.nombre||' '||:NEW.username); 
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'TRG_USER', SYSDATE, VCOD || ' - ' || VMES);
END;
/
ALTER TRIGGER "ADMIN1"."TRG_USER" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_FACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."ACTUALIZAR_FACTURA" (
    fac_id NUMBER,
    tot NUMBER
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    UPDATE Factura
    SET total = tot, estado = 1
    WHERE id_factura = fac_id;
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'ACTUALIZAR_FACTURA', SYSDATE, VCOD || ' - '|| VMES);
END ACTUALIZAR_FACTURA;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."ACTUALIZAR_USUARIO" (
    usuario_id NUMBER,
    nomb VARCHAR2,
    apelli VARCHAR2,
    mail VARCHAR2,
    direc VARCHAR2,
    userna VARCHAR2,
    pass VARCHAR2,
    tarj VARCHAR2,
    pin_us VARCHAR2
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    UPDATE Usuario
    SET nombre = nomb,
    apellido = apelli,
    correo = mail,
    direccion = direc,
    username = userna,
    password = pass,
    tarjeta = tarj,
    pin = pin_us,
    fecha = SYSDATE,
    activo = 1,
    id_rol = 2
WHERE id_usuario = usuario_id;
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'ACTUALIZAR_USUARIO', SYSDATE, VCOD || ' - '|| VMES);
END ACTUALIZAR_USUARIO;

/
--------------------------------------------------------
--  DDL for Procedure CREAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."CREAR_USUARIO" (
    nomb VARCHAR2,
    apelli VARCHAR2,
    mail VARCHAR2,
    direc VARCHAR2,
    userna VARCHAR2,
    pass VARCHAR2,
    tarj VARCHAR2,
    pin_us VARCHAR2
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    INSERT INTO Usuario (nombre, apellido, correo, direccion, username, password, tarjeta, pin, fecha, activo, id_rol)
    VALUES (nomb, apelli, mail, direc, userna, pass, tarj, pin_us, SYSDATE, 0, 2);
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'CREAR_USUARIO', SYSDATE, VCOD || ' - '|| VMES);
END CREAR_USUARIO;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_PRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."DELETE_PRODUCTO" (
    p_id_producto IN NUMBER
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    DELETE FROM producto WHERE id_producto = p_id_producto;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Producto no encontrado');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'DELETE_PRODUCTO', SYSDATE, VCOD || ' - ' || VMES);
END DELETE_PRODUCTO;

/
--------------------------------------------------------
--  DDL for Procedure FIND_PRODUCTO_BY_CAT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."FIND_PRODUCTO_BY_CAT" (
    cat_id NUMBER, 
    p_resultado OUT SYS_REFCURSOR
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    OPEN p_resultado FOR
    SELECT *
    FROM producto
    WHERE id_categoria = cat_id;
EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'FIND_PRODUCTO_BY_CAT', SYSDATE, VCOD || ' - ' || VMES);
END FIND_PRODUCTO_BY_CAT;

/
--------------------------------------------------------
--  DDL for Procedure FIND_PRODUCTO_BY_NOMBRE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."FIND_PRODUCTO_BY_NOMBRE" (
    p_nombre VARCHAR2, 
    p_resultado OUT SYS_REFCURSOR
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    OPEN p_resultado FOR
    SELECT *
    FROM producto
    WHERE REGEXP_LIKE(UPPER(nombre), UPPER(p_nombre));
EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'FIND_PRODUCTO_BY_NOMBRE', SYSDATE, VCOD || ' - ' || VMES);
END FIND_PRODUCTO_BY_NOMBRE;

/
--------------------------------------------------------
--  DDL for Procedure GET_CATEGORIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."GET_CATEGORIAS" (
    p_resultado OUT SYS_REFCURSOR
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    OPEN p_resultado FOR
    SELECT * FROM categoria;
EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'GET_CATEGORIAS', SYSDATE, VCOD || ' - ' || VMES);
END GET_CATEGORIAS; 

/
--------------------------------------------------------
--  DDL for Procedure GETFACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."GETFACTURA" (
    p_Id_Factura INT
) IS
    v_fecha  FACTURA.fecha%TYPE;
    v_total  FACTURA.total%TYPE;
    v_estado FACTURA.estado%TYPE;
    v_mes     VARCHAR2(4000);
    v_cod     NUMBER;
BEGIN
    SELECT fecha, total, estado
    INTO v_fecha, v_total, v_estado
    FROM FACTURA
    WHERE Id_Factura = p_Id_Factura;

    DBMS_OUTPUT.PUT_LINE('=========================================');
    DBMS_OUTPUT.PUT_LINE('                FACTURA                  ');
    DBMS_OUTPUT.PUT_LINE('=========================================');
    DBMS_OUTPUT.PUT_LINE('Factura ID:       ' || p_Id_Factura);
    DBMS_OUTPUT.PUT_LINE('Fecha:            ' || TO_CHAR(v_fecha, 'DD-MON-YYYY'));
    DBMS_OUTPUT.PUT_LINE('-----------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Total:            $' || TO_CHAR(v_total, '999,999.99'));
    DBMS_OUTPUT.PUT_LINE('-----------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Estado:           ' || CASE v_estado
                                           WHEN 1 THEN 'Activo'
                                           ELSE 'Inactivo'
                                       END);
    DBMS_OUTPUT.PUT_LINE('=========================================');
    DBMS_OUTPUT.PUT_LINE('  ¡Gracias por su compra!                ');
    DBMS_OUTPUT.PUT_LINE('=========================================');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se encontrÓ la factura con el ID ' || p_Id_Factura);
    WHEN OTHERS THEN
        v_mes := SQLERRM;
        v_cod := SQLCODE;
        INSERT INTO ERRORES_AUDIT VALUES (USER, 'EXISTE_USU',SYSDATE, v_cod || ' - '|| v_mes);
        DBMS_OUTPUT.PUT_LINE('Ocurri� un error: ' || v_mes);
END getFactura;

/
--------------------------------------------------------
--  DDL for Procedure GET_PRODUCTO_BY_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."GET_PRODUCTO_BY_ID" (
    p_id_producto IN NUMBER, 
    p_resultado OUT SYS_REFCURSOR
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    OPEN p_resultado FOR
    SELECT * FROM producto WHERE id_producto = p_id_producto;
EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'GET_PRODUCTO_BY_ID', SYSDATE, VCOD || ' - ' || VMES);
END GET_PRODUCTO_BY_ID;

/
--------------------------------------------------------
--  DDL for Procedure GET_PRODUCTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."GET_PRODUCTOS" (
    p_resultado OUT SYS_REFCURSOR
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN 
    OPEN p_resultado FOR
    SELECT * FROM producto;
EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'GET_PRODUCTOS', SYSDATE, VCOD || ' - ' || VMES);
END GET_PRODUCTOS;

/
--------------------------------------------------------
--  DDL for Procedure GET_USU_USER_CORRECS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."GET_USU_USER_CORRECS" (
    user_name VARCHAR2,
    corre VARCHAR2,
    CSDATOS OUT SYS_REFCURSOR
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    OPEN CSDATOS FOR SELECT id_usuario,nombre, apellido, correo, direccion, username, password, tarjeta, pin, fecha, activo, id_rol 
    FROM Usuario
    WHERE username = user_name OR correo = corre;
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_USU_USER_CORRECS', SYSDATE, VCOD || ' - '|| VMES);
END GET_USU_USER_CORRECS;

/
--------------------------------------------------------
--  DDL for Procedure GET_USU_USERCS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."GET_USU_USERCS" (
    user_name VARCHAR2,
    CSDATOS OUT SYS_REFCURSOR
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
    dinamico VARCHAR2(4000);
BEGIN
    dinamico := 'SELECT id_usuario, nombre, apellido, correo, direccion, username, password, tarjeta, pin, fecha, activo, id_rol FROM Usuario WHERE username = :user_name';
    OPEN CSDATOS FOR dinamico
    USING user_name;
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_USU_USERCS', SYSDATE, VCOD || ' - '|| VMES);
END GET_USU_USERCS;

/
--------------------------------------------------------
--  DDL for Procedure GET_USU_USER_PASSCS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."GET_USU_USER_PASSCS" (
    user_name VARCHAR2,
    pass VARCHAR2,
    CSDATOS OUT SYS_REFCURSOR
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    OPEN CSDATOS FOR SELECT id_usuario,nombre, apellido, correo, direccion, username, password, tarjeta, pin, fecha, activo, id_rol 
    FROM Usuario
    WHERE username = user_name AND password = pass;
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_USU_USER_PASSCS', SYSDATE, VCOD || ' - '|| VMES);
END GET_USU_USER_PASSCS;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_VENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."INSERTAR_VENTA" (
    fac_id NUMBER,
    prod_id NUMBER,
    prec NUMBER,
    cant NUMBER
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    INSERT INTO Venta (id_factura, id_producto, precio, cantidad)
    VALUES (fac_id, prod_id,prec, cant);
    UPDATE Producto
    SET existencias = existencias-cant
    WHERE id_producto = prod_id;
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'INSERTAR_VENTA', SYSDATE, VCOD || ' - '|| VMES);
END INSERTAR_VENTA;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_PRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "ADMIN1"."INSERT_PRODUCTO" (
    p_id_producto IN NUMBER,
    p_id_categoria IN NUMBER,
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_precio IN NUMBER,
    p_existencias IN NUMBER,
    p_ruta_imagen IN VARCHAR2,
    p_activo IN NUMBER
) AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN

    IF p_id_producto IS NULL THEN
        INSERT INTO producto (id_categoria, nombre, descripcion, precio, existencias, ruta_imagen, activo)
        VALUES (p_id_categoria, p_nombre, p_descripcion, p_precio, p_existencias, p_ruta_imagen, p_activo);
    ELSE
        UPDATE producto
        SET id_categoria = p_id_categoria,
            nombre = p_nombre,
            descripcion = p_descripcion,
            precio = p_precio,
            existencias = p_existencias,
            ruta_imagen = p_ruta_imagen,
            activo = p_activo
        WHERE id_producto = p_id_producto;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'INSERT_PRODUCTO', SYSDATE, VCOD || ' - ' || VMES);
END INSERT_PRODUCTO;

/
--------------------------------------------------------
--  DDL for Package PKG_CATEGORIA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "ADMIN1"."PKG_CATEGORIA" AS
    FUNCTION GET_VENTAS RETURN SYS_REFCURSOR;
    PROCEDURE GET_CATEGORIA_BY_ID (
        p_id_categoria IN NUMBER, 
        p_resultado OUT SYS_REFCURSOR
    );
    PROCEDURE GET_CATEGORIAS (
        p_resultado OUT SYS_REFCURSOR
    );
END PKG_CATEGORIA;

/
--------------------------------------------------------
--  DDL for Package PKG_PRODUCTO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "ADMIN1"."PKG_PRODUCTO" AS
    FUNCTION GET_VENTAS RETURN SYS_REFCURSOR;
    PROCEDURE DELETE_PRODUCTO (
        p_id_producto IN NUMBER
    );
    PROCEDURE FIND_PRODUCTO_BY_NOMBRE (
        p_nombre VARCHAR2, 
        p_resultado OUT SYS_REFCURSOR
    );
    PROCEDURE GET_PRODUCTO_BY_ID (
        p_id_producto IN NUMBER, 
        p_resultado OUT SYS_REFCURSOR
    );
    PROCEDURE GET_PRODUCTOS (
        p_resultado OUT SYS_REFCURSOR
    );
    PROCEDURE INSERT_PRODUCTO (
        p_id_producto IN NUMBER,
        p_id_categoria IN NUMBER,
        p_nombre IN VARCHAR2,
        p_descripcion IN VARCHAR2,
        p_precio IN NUMBER,
        p_existencias IN NUMBER,
        p_ruta_imagen IN VARCHAR2,
        p_activo IN NUMBER
    );
END PKG_PRODUCTO;

/
--------------------------------------------------------
--  DDL for Package PKG_USER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "ADMIN1"."PKG_USER" AS
    FUNCTION EXISTE_USU (
        user_name VARCHAR2,
        correo_user VARCHAR2
    ) RETURN NUMBER;
    FUNCTION GET_USU_USER (
        user_name VARCHAR2
    ) RETURN SYS_REFCURSOR;
    FUNCTION GET_USU_USER_CORRE (
        user_name VARCHAR2,
        corre VARCHAR2
    ) RETURN SYS_REFCURSOR;
    FUNCTION GET_USU_USER_PASS (
        user_name VARCHAR2,
        pass VARCHAR2
    ) RETURN SYS_REFCURSOR;
    PROCEDURE ACTUALIZAR_USUARIO (
        usuario_id NUMBER,
        nomb VARCHAR2,
        apelli VARCHAR2,
        mail VARCHAR2,
        direc VARCHAR2,
        userna VARCHAR2,
        pass VARCHAR2,
        tarj VARCHAR2,
        pin_us VARCHAR2
    );
    PROCEDURE CREAR_USUARIO (
        nomb VARCHAR2,
        apelli VARCHAR2,
        mail VARCHAR2,
        direc VARCHAR2,
        userna VARCHAR2,
        pass VARCHAR2,
        tarj VARCHAR2,
        pin_us VARCHAR2
    );
    PROCEDURE GET_USU_USER_CORRECS (
        user_name VARCHAR2,
        corre VARCHAR2,
        CSDATOS OUT SYS_REFCURSOR
    );
    PROCEDURE GET_USU_USER_PASSCS (
        user_name VARCHAR2,
        pass VARCHAR2,
        CSDATOS OUT SYS_REFCURSOR
    );
    PROCEDURE GET_USU_USERCS (
        user_name VARCHAR2,
        CSDATOS OUT SYS_REFCURSOR
    );
END PKG_USER;

/
--------------------------------------------------------
--  DDL for Package PKG_VENTAS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "ADMIN1"."PKG_VENTAS" AS
    FUNCTION CREAR_FACTURA (
        usu_id NUMBER
    ) RETURN NUMBER;
    FUNCTION GET_VENTAS RETURN SYS_REFCURSOR;
    PROCEDURE INSERTAR_VENTA (
        fac_id NUMBER, 
        prod_id NUMBER, 
        prec NUMBER, 
        cant NUMBER
    );
    PROCEDURE ACTUALIZAR_FACTURA (
        fac_id NUMBER, 
        tot NUMBER
    );
    PROCEDURE getFactura (
        p_Id_Factura INT
    );
END PKG_VENTAS;

/
--------------------------------------------------------
--  DDL for Function CREAR_FACTURA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "ADMIN1"."CREAR_FACTURA" (
    usu_id NUMBER
) RETURN 
NUMBER IS
    v_id_factura NUMBER;
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    INSERT INTO factura (id_usuario, fecha)
    VALUES (usu_id, SYSDATE)
    RETURNING id_factura INTO v_id_factura;

    RETURN v_id_factura;

EXCEPTION
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'CREAR_FACTURA', SYSDATE, VCOD || ' - '|| VMES);
END CREAR_FACTURA;

/
--------------------------------------------------------
--  DDL for Function EXISTE_USU
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "ADMIN1"."EXISTE_USU" (
    user_name VARCHAR2,
    correo_user VARCHAR2
) RETURN 
NUMBER IS
    cantidad NUMBER;
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cantidad
    FROM Usuario
    WHERE username = user_name OR correo = correo_user;

    RETURN cantidad;

EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'EXISTE_USU', SYSDATE, VCOD || ' - '|| VMES);
END EXISTE_USU;

/
--------------------------------------------------------
--  DDL for Function GET_USUARIO_BY_USERNAME
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "ADMIN1"."GET_USUARIO_BY_USERNAME" (
    p_username IN VARCHAR2
) RETURN SYS_REFCURSOR IS
    resultado SYS_REFCURSOR;
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    OPEN resultado FOR
    SELECT u.id_usuario, u.username, u.password, u.id_rol
    FROM usuario u
    WHERE u.username = p_username;

    RETURN resultado;

EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'GET_USUARIO_BY_USERNAME', SYSDATE, VCOD || ' - ' || VMES);
        RAISE;
END GET_USUARIO_BY_USERNAME;

/
--------------------------------------------------------
--  DDL for Function GET_USU_USER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "ADMIN1"."GET_USU_USER" (
    user_name VARCHAR2
) RETURN SYS_REFCURSOR
AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
    CDATOS SYS_REFCURSOR;
BEGIN
    GET_USU_USERCS(user_name, CDATOS);

    RETURN CDATOS;

EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_USU_USER', SYSDATE, VCOD || ' - '|| VMES);
END GET_USU_USER;

/
--------------------------------------------------------
--  DDL for Function GET_USU_USER_CORRE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "ADMIN1"."GET_USU_USER_CORRE" (
    user_name VARCHAR2,
    corre VARCHAR2
) RETURN SYS_REFCURSOR
AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
    CDATOS SYS_REFCURSOR;
BEGIN
    GET_USU_USER_CORRECS(user_name,corre,CDATOS);

    RETURN CDATOS;

EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_USU_USER_CORRE', SYSDATE, VCOD || ' - '|| VMES);
END GET_USU_USER_CORRE;

/
--------------------------------------------------------
--  DDL for Function GET_USU_USER_PASS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "ADMIN1"."GET_USU_USER_PASS" (
    user_name VARCHAR2,
    pass VARCHAR2
) RETURN SYS_REFCURSOR
AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
    CDATOS SYS_REFCURSOR;
BEGIN
    GET_USU_USER_PASSCS(user_name,pass,CDATOS);

    RETURN CDATOS;

EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_USU_USER_PASS', SYSDATE, VCOD || ' - '|| VMES);
END GET_USU_USER_PASS;

/
--------------------------------------------------------
--  DDL for Function GET_VENTAS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "ADMIN1"."GET_VENTAS" RETURN SYS_REFCURSOR IS
    resultado SYS_REFCURSOR;
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    OPEN resultado FOR SELECT * FROM VENTA;

    RETURN resultado;

EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_VENTAS', SYSDATE, VCOD || ' - '|| VMES);
END GET_VENTAS;

/
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."ROLES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."ROLES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."FACTURA" MODIFY ("ID_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."FACTURA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."FACTURA" ADD PRIMARY KEY ("ID_FACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."CATEGORIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."CATEGORIA" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."CATEGORIA" ADD PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."VENTA" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."VENTA" MODIFY ("ID_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."VENTA" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."VENTA" ADD PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."PRODUCTO" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."PRODUCTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."PRODUCTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."PRODUCTO" ADD PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."USUARIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."USUARIO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."USUARIO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."USUARIO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."USUARIO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."USUARIO" MODIFY ("TARJETA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."USUARIO" MODIFY ("PIN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN1"."USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."FACTURA" ADD CONSTRAINT "FK_FACTURA_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMIN1"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."PRODUCTO" ADD CONSTRAINT "FK_PRODUCTO_CATEGORIA" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "ADMIN1"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."USUARIO" ADD CONSTRAINT "FK_USUARIO_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "ADMIN1"."ROLES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "ADMIN1"."VENTA" ADD CONSTRAINT "FK_VENTA_FACTURA" FOREIGN KEY ("ID_FACTURA")
	  REFERENCES "ADMIN1"."FACTURA" ("ID_FACTURA") ENABLE;
  ALTER TABLE "ADMIN1"."VENTA" ADD CONSTRAINT "FK_VENTA_PRODUCTO" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "ADMIN1"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
