CREATE OR REPLACE FUNCTION GET_VENTAS RETURN SYS_REFCURSOR IS
    resultado SYS_REFCURSOR;
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    OPEN resultado FOR SELECT * FROM VENTA;
    
    RETURN resultado;
    
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_VENTAS', SYSDATE, VCOD || ' - '|| VMES);
END GET_VENTAS;

CREATE OR REPLACE FUNCTION GET_USUARIO_BY_USERNAME (
    p_username IN VARCHAR2
) RETURN SYS_REFCURSOR IS
    resultado SYS_REFCURSOR;
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    OPEN resultado FOR
    SELECT u.id_usuario, u.username, u.password, u.id_rol
    FROM usuario u
    WHERE u.username = p_username;
    
    RETURN resultado;

EXCEPTION
    WHEN OTHERS THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT (USUARIO, ORIGEN, FECHA, VERROR)
        VALUES (USER, 'GET_USUARIO_BY_USERNAME', SYSDATE, VCOD || ' - ' || VMES);
        RAISE;
END GET_USUARIO_BY_USERNAME;

CREATE OR REPLACE FUNCTION CREAR_FACTURA (
    usu_id NUMBER
) RETURN 
NUMBER IS
    v_id_factura NUMBER;
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    INSERT INTO factura (id_usuario, fecha)
    VALUES (usu_id, SYSDATE)
    RETURNING id_factura INTO v_id_factura;
    
    RETURN v_id_factura;
    
EXCEPTION
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'CREAR_FACTURA', SYSDATE, VCOD || ' - '|| VMES);
END CREAR_FACTURA;

CREATE OR REPLACE FUNCTION GET_USU_USER_PASS (
    user_name VARCHAR2,
    pass VARCHAR2
) RETURN SYS_REFCURSOR
AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
    CDATOS SYS_REFCURSOR;
BEGIN
    GET_USU_USER_PASSCS(user_name,pass,CDATOS);
    
    RETURN CDATOS;
    
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_USU_USER_PASS', SYSDATE, VCOD || ' - '|| VMES);
END GET_USU_USER_PASS;

CREATE OR REPLACE FUNCTION GET_USU_USER_CORRE (
    user_name VARCHAR2,
    corre VARCHAR2
) RETURN SYS_REFCURSOR
AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
    CDATOS SYS_REFCURSOR;
BEGIN
    GET_USU_USER_CORRECS(user_name,corre,CDATOS);
    
    RETURN CDATOS;
    
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_USU_USER_CORRE', SYSDATE, VCOD || ' - '|| VMES);
END GET_USU_USER_CORRE;

CREATE OR REPLACE FUNCTION GET_USU_USER (
    user_name VARCHAR2
) RETURN SYS_REFCURSOR
AS
    VMES VARCHAR2(4000);
    VCOD NUMBER;
    CDATOS SYS_REFCURSOR;
BEGIN
    GET_USU_USERCS(user_name, CDATOS);
    
    RETURN CDATOS;
    
EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'GET_USU_USER', SYSDATE, VCOD || ' - '|| VMES);
END GET_USU_USER;

CREATE OR REPLACE FUNCTION EXISTE_USU (
    user_name VARCHAR2,
    correo_user VARCHAR2
) RETURN 
NUMBER IS
    cantidad NUMBER;
    VMES VARCHAR2(4000);
    VCOD NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO cantidad
    FROM Usuario
    WHERE username = user_name OR correo = correo_user;
    
    RETURN cantidad;

EXCEPTION    
    WHEN OTHERS THEN  
    VMES := SQLERRM;
    VCOD := SQLCODE;
    INSERT INTO ERRORES_AUDIT VALUES (USER, 'EXISTE_USU', SYSDATE, VCOD || ' - '|| VMES);
END EXISTE_USU;
