CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20) NOT NULL
);

CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(2048) NOT NULL,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(100) NOT NULL,
    tarjeta VARCHAR2(16) NOT NULL,
    pin VARCHAR2(4) NOT NULL,
    fecha DATE,
    activo NUMBER(1),
    id_rol NUMBER
);

ALTER TABLE usuario
ADD CONSTRAINT fk_usuario_rol 
    FOREIGN KEY (id_rol) 
    REFERENCES roles(id);

CREATE TABLE categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL,
    tipo VARCHAR2(30) NOT NULL,
    activo NUMBER(1)
);

CREATE TABLE producto (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria NUMBER NOT NULL,
    nombre VARCHAR2(1000) NOT NULL,
    descripcion VARCHAR2(1600) NOT NULL,
    precio NUMBER,
    existencias NUMBER,
    ruta_imagen VARCHAR2(2048),
    activo NUMBER(1)
);

ALTER TABLE producto
ADD CONSTRAINT fk_producto_categoria 
    FOREIGN KEY (id_categoria) 
    REFERENCES categoria(id_categoria);

CREATE TABLE factura (
    id_factura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    fecha DATE,
    total NUMBER,
    estado NUMBER
);

ALTER TABLE factura
ADD CONSTRAINT fk_factura_usuario 
    FOREIGN KEY (id_usuario) 
    REFERENCES usuario(id_usuario);

CREATE TABLE venta (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    precio NUMBER,
    cantidad NUMBER
);

ALTER TABLE venta
ADD CONSTRAINT fk_venta_factura 
    FOREIGN KEY (id_factura) 
    REFERENCES factura(id_factura);
ALTER TABLE venta
ADD CONSTRAINT fk_venta_producto 
    FOREIGN KEY (id_producto) 
    REFERENCES producto(id_producto);

CREATE TABLE ERRORES_AUDIT (
    USUARIO VARCHAR2(50),
    ORIGEN VARCHAR2(50),
    FECHA DATE,
    VERROR VARCHAR2(600)
);

CREATE TABLE MENSAJE_TRIGGERS (
    VUSER VARCHAR2(50),
    VMENSAJE VARCHAR2(200)
);
